### ISSUE TITLE
Failed running yarn build from root

### ISSUE THREAD

**Issue by jdeanwaite** [tommedema/serverless-mono-example#3] opened 2018-08-25 20:30 UTC
First off, just want to say this is a great starter project, and perfect timing! It seems every time I start researching a new stack/paradigm someone just released something 4 days prior!

Just a quick issue while testing out the repo: when I run `yarn build` from the root dir per the README documentation, I receive the following Typescript errors:

```
yarn run v1.9.2
$ tsc -b .
node_modules/@types/node/index.d.ts:34:22 - error TS6305: Output file '/Users/justin/WebstormProjects/serverless-mono-example/packages/typesnode_modules/@types/node/inspector.d.ts' has not been built from source file '/Users/justin/WebstormProjects/serverless-mono-example/node_modules/@types/node/inspector.d.ts'.

34 /// <reference path="./inspector.d.ts" />
                        ~~~~~~~~~~~~~~~~

packages/sls-random/src/index.ts:6:8 - error TS2307: Cannot find module 'aws-lambda'.

6 } from 'aws-lambda'
         ~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

However, building from within the individual packages appears to work just fine.

**Comment by tommedema** [comment] 2018-08-26 22:41
Thanks!

I added `aws-lambda` as a dev dependency under `sls-random` because it's only there for type checking. Did you run `yarn install` prior to `yarn build`? Without the `--production` flag?

**Comment by tommedema** [comment] 2018-08-27 17:41
@jdeanwaite not exactly sure but I suspect there is an issue related to path mapping and/or inclusion/exclusion of input files

reason is that your error contains an invalid path `serverless-mono-example/packages/typesnode_modules` where obviously it should be `types/node_modules`. There is a missing `/`.

Are you sure that `node_modules` is being excluded?

**Comment by tommedema** [comment] 2018-08-27 18:12
I can now reproduce this issue. Not sure when it started appearing..

Not sure about a fix yet either. Will give it a try.

**Comment by tommedema** [comment] 2018-08-27 18:43
@jdeanwaite problem is that the root `tsconfig.json` should not have a reference to `types`, because types is not supposed to be build. It only contains type definitions for compilation reasons used by typeRoots

However when removing it I'm seeing strange behavior where output files are not written to their outDirs. Will investigate further

**Comment by tommedema** [comment] 2018-08-27 18:57
Fixed in https://github.com/tommedema/serverless-mono-example/commit/627ca9b8f36bf8b2c95e5484e318389a259c9c1d

**Closed by tommedema** 2018-08-27 18:57 UTC

**Comment by jdeanwaite** [comment] 2018-08-27 19:01
Nice. Will check out the commit and massage it into my project.
